export const PIECE_FORM_FIELD_NAMES = {
  accessionNumber: 'accessionNumber',
  barcode: 'barcode',
  callNumber: 'callNumber',
  chronology: 'chronology',
  claimingInterval: 'claimingInterval',
  comment: 'comment',
  copyNumber: 'copyNumber',
  discoverySuppress: 'discoverySuppress',
  displayOnHolding: 'displayOnHolding',
  displaySummary: 'displaySummary',
  displayToPublic: 'displayToPublic',
  enumeration: 'enumeration',
  externalNote: 'externalNote',
  format: 'format',
  holdingId: 'holdingId',
  internalNote: 'internalNote',
  isBound: 'isBound',
  isCreateItem: 'isCreateItem',
  locationId: 'locationId',
  receiptDate: 'receiptDate',
  receivingStatus: 'receivingStatus',
  receivingTenantId: 'receivingTenantId',
  sequenceNumber: 'sequenceNumber',
  supplement: 'supplement',
};
